# Compiler and flags
CC      := gcc
CFLAGS  := -g -Wall -MMD -Iinclude -march=native -msse4.2 -mavx2 -mfma
LDFLAGS := -lm

# Project structure
BUILD_DIR   := build
SRC_DIR     := src
INCLUDE_DIR := include
OBJ_DIR     := $(BUILD_DIR)/obj
BIN_DIR     := $(BUILD_DIR)
LIB_DIR     := $(BUILD_DIR)/lib
DATA_DIR    := snapshots

# Library configuration
LIB_NAME    := GigaVector
LIB_VERSION := 0.0.1 
STATIC_LIB  := $(LIB_DIR)/lib$(LIB_NAME).a

# Find all source files for the library
SRC_FILES   := $(shell find $(SRC_DIR) -name "*.c")
# Define the main source file for the executable
MAIN_FILE   := main.c

# Generate object file paths
# Library objects (from SRC_DIR)
LIB_OBJS    := $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(SRC_FILES))
# Main executable object (from MAIN_FILE at root)
MAIN_OBJ    := $(OBJ_DIR)/$(MAIN_FILE:.c=.o)
# All objects needed for the main executable
ALL_OBJS    := $(LIB_OBJS) $(MAIN_OBJ)

# Dependencies: .d files generated by -MMD
DEPS := $(ALL_OBJS:.o=.d)

# Default target: build the main executable
.PHONY: all
all: $(BIN_DIR)/main

.PHONY: run
run: $(BIN_DIR)/main
	@mkdir -p $(DATA_DIR)
	@echo "Running demo with outputs in $(DATA_DIR)/"
	@cd $(DATA_DIR) && GV_DATA_DIR="$(abspath $(DATA_DIR))" GV_WAL_DIR="$(abspath $(DATA_DIR))" ../main

# Build the main executable
$(BIN_DIR)/main: $(ALL_OBJS) $(STATIC_LIB)
	@mkdir -p $(BIN_DIR)
	$(CC) $(CFLAGS) $(MAIN_OBJ) $(LDFLAGS) -L$(LIB_DIR) -l$(LIB_NAME) -o $@
	@echo "Built main executable: $@"

# Build the static library
.PHONY: lib
lib: $(STATIC_LIB)

$(STATIC_LIB): $(LIB_OBJS)
	@mkdir -p $(LIB_DIR)
	ar rcs $@ $^
	@echo "Built static library: $@"

# Compile library source files (from SRC_DIR)
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) -c $< -o $@
	@echo "Compiled $< -> $@"

# Compile main source file (from project root)
$(OBJ_DIR)/$(MAIN_FILE:.c=.o): $(MAIN_FILE)
	@mkdir -p $(OBJ_DIR)
	$(CC) $(CFLAGS) -c $< -o $@
	@echo "Compiled $< -> $@"

# Clean build artifacts
.PHONY: clean
clean:
	rm -rf $(BUILD_DIR) a.out *.d $(OBJ_DIR)/*.d
	@echo "Cleaned build artifacts"

-include $(DEPS)