apiVersion: v1
kind: Service
metadata:
  name: {{ include "gigavector.fullname" . }}
  labels:
    {{- include "gigavector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.server.port }}
      targetPort: http
  selector:
    {{- include "gigavector.selectorLabels" . | nindent 4 }}
